# Site settings
title: Themistoklis Diamantopoulos
email: thdiaman@issel.ee.auth.gr
description: Personal website of Themistoklis Diamantopoulos # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://thdiaman.github.io" # the base hostname & protocol for your site
github_username:  thdiaman
twitter:
  username: thdiaman
social:
  links:
    - https://twitter.com/thdiaman
    - https://www.linkedin.com/in/thdiaman
    - https://github.com/thdiaman

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "PhD Candidate \ Research Associate"
excerpt_separator: "<!--more-->"
collections:
  publications:
  software:
    output: true

gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

# SEO stuff
# google_author: ""
google_site_verification: "bS3YizW4pMEylO5bJeQFGflvuaD1lF6672Pbyp52AXY"
# bing_webmastertools_id: ""