# Site settings
title: Themistoklis Diamantopoulos
email: thdiaman@issel.ee.auth.gr
description: > # this means to ignore newlines until "baseurl:"
  (c) 2016 Themistoklis Diamantopoulos
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://thdiaman.github.io" # the base hostname & protocol for your site
github_username:  thdiaman

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "PhD Candidate \ Research Associate"
excerpt_separator: "<!--more-->"
collections:
- publications

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""